name: Run Unit Test and Upload Coverage Report

on:
  push:
    branches: [ "main", "sachin_updates" "navdeep_updates"]
  pull_request:
    branches: [ "main" ]
    types: [opened]
  workflow_dispatch:

jobs:
  build-run-upload:
    runs-on: ubuntu-22.04
    
    steps:
      - uses: actions/checkout@v3
        with:
          path: CleanSweep

      # Install ROS 2 Humble
      - name: Install ROS 2 Humble
        run: |
          sudo apt update
          sudo apt install -y software-properties-common
          sudo add-apt-repository universe
          sudo apt update && sudo apt install -y curl
          sudo curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(. /etc/os-release && echo $UBUNTU_CODENAME) main" | sudo tee /etc/apt/sources.list.d/ros2.list > /dev/null
          sudo apt update
          sudo apt install -y ros-humble-ros-base
          sudo apt install -y python3-colcon-common-extensions
          sudo apt install -y ros-humble-cv-bridge
          sudo apt install -y ros-humble-ament-cmake-gtest

      # Install dependencies for coverage and documentation
      - name: Install build packages
        run: |
          sudo apt install -y doxygen lcov gcovr
          sudo apt install -y libopencv-dev

      # Source ROS 2
      - name: Source ROS 2
        run: |
          source /opt/ros/humble/setup.bash
          echo "source /opt/ros/humble/setup.bash" >> ~/.bashrc

      # Create workspace and build
      - name: Build and Test
        run: |
          mkdir -p ros2_ws/src
          mv CleanSweep ros2_ws/src/  # Move instead of copy
          cd ros2_ws
          source /opt/ros/humble/setup.bash
          colcon build --cmake-args -DWANT_COVERAGE=ON
          source install/setup.bash
          colcon test --packages-select cleansweep
          cd build/cleansweep
          make coverage
          lcov --remove coverage.info '/opt/ros/*' '/usr/*' '*/test/*' '*/build/*' '*/install/*' '*_deps/*' --output-file coverage.info
          lcov --extract coverage.info '*/CleanSweep/src/*' '*/CleanSweep/include/*' --output-file coverage.info

      # Upload coverage result to CodeCov
      - name: Upload coverage result to CodeCov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ros2_ws/build/cleansweep/coverage.info  # Updated path
          fail_ci_if_error: true
          verbose: true
          disable_search: true
          plugin: none